### ISSUE TITLE
Modifying parts of css

### ISSUE THREAD

**Issue by thoberre** [upmin/upmin-admin-ruby#145]
Maybe related to my lack of experience with engines...

I would like to override parts of the css for upmin. Particulary i need to have a top margin to all body on pages in upmin. What is the best way to override this without duplication the entire set of css files (the main part have incudes as well?

**Comment by GoGoYellowScreen** [comment]
(Not a collaborator on upmin but I ran into this too and thought what I learned might be useful).

I also needed to do this, to allow for a taller than standard boostrap nav.  I did it by adding a custom class to the body, and then calling it in the regular app's css.  

I made a new file:  app/views/layouts/upmin/application.html.haml

In application.html.haml:

!!!
%html
  %head
    %title
      Upmin Dashboard
    = stylesheet_link_tag("upmin/application", media: "all")
    = javascript_include_tag("upmin/application")
    = csrf_meta_tags

    %link{href: "//cdn.jsdelivr.net/bootstrap/3.2.0/css/bootstrap.min.css", rel: "stylesheet", type: "text/css"}
    %link{href: "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", rel: "stylesheet"}
    %script{src: "//cdn.jsdelivr.net/bootstrap/3.2.0/js/bootstrap.min.js"}
    %script{src: "//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.3/moment.min.js"}

    - if content_for?(:head)
      = yield(:head)


  %body{ id: "upmin-body", class: body_classes, data: body_data.merge(root_path: root_path), :style => "padding-top: 65px;" }
    .page-wrap
      = render('layouts/upmin/navbar')
      = render('layouts/upmin/flash')
      = yield

    -# = render('layouts/footer')

    - if content_for?(:javascript)
      = yield(:javascript)

Note the body id "upmin-body"

And then I did standard css stuff in the application.css.scss file with #upmin-body

**Comment by joncalhoun** [comment]
With all Rails engine (at least to my knowledge) you can create local files in your app (eg `app/views/layouts/upmin/application.html.haml`) and the engine will prefer your local file over its own. This basically means that to override css, the easiest way is often just to clone the application.html.haml file, add it to your app, then add in the changes you need (eg load another css file).

Aside from that I'm not 100% sure of the best way because I haven't spent much time on this. If this solution ends up being an annoyance for some reason let me know, but I don't see the application.html.haml file changing frequently so this shouldn't be too hard to maintain.

**Comment by thoberre** [comment]
Tanks for quick reply from you both! I was a bit reluctant to make the application file local, so this is right on!
