### ISSUE TITLE
"Could not find generator 'upmin:install'"

### ISSUE THREAD

**Issue by joshukraine** [upmin/upmin-admin-ruby#173]
I'm running Ruby 2.2.2 (via rbenv) and Rails 4.2.1. After installing the gem per the Upmin readme instructions, I try to install it with `rails g upmin:install`. But all I get is the error: 
```sh
Could not find generator 'upmin:install'. Maybe you meant 'migration' or 'kaminari:views' or 'css:assets'
Run `rails generate --help` for more options.
```
Thoughts?

**Comment by mbrookes** [comment]
Thanks, I've fixed up the README. 

The README is correct for master, but the published gem is quite far behind at the moment, so doesn't have the generator.

If you want to live on the edge, you can point your gemfile entry to the github repo - I would pick a specific commit for stability, otherwise you might find it up min:admin out from under you and potentially breaks something.

    gem 'upmin-admin-ruby', :github => 'upmin/upmin-admin-ruby', :ref => 'f036510b74'
